
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter (if available)
      run: npm run lint || echo "Lint script not available"
      continue-on-error: true
      
    - name: Check Prettier formatting (if available)
      run: npm run format:check || echo "Format check script not available"
      continue-on-error: true
      
    - name: Run tests
      run: npm run test || echo "Test script not available"
      continue-on-error: true
      
    - name: Build project
      run: npm run build
      
    - name: Install Playwright (if available)
      run: npx playwright install || echo "Playwright not available"
      continue-on-error: true
      
    - name: Run E2E tests (if available)
      run: npm run test:e2e || echo "E2E tests not available"
      continue-on-error: true

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
